{% set version = "1.1.2" %}

package:
  name: mercantile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mercantile/mercantile-{{ version }}.tar.gz
  sha256: 6681c0be3b3d8ea1d88d7f9cff56993782fb7de1e9df420ad9c48f93a859394d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - mercantile=mercantile.scripts:cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - click >=3.0

test:
  imports:
    - mercantile
    - mercantile.scripts
  commands:
    - mercantile --help

about:
  home: https://github.com/sgillies/mercantile
  license: BSD-3-Clause
  summary: 'Spherical mercator and XYZ tile utilities'
  license_family: BSD

extra:
  recipe-maintainers:
    - ocefpaf
