{% set version = "0.10.0" %}

package:
  name: mercantile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mercantile/mercantile-{{ version }}.tar.gz
  sha256: 4b6bdba8ed134092d6f9f040b3e4d979db3791ba6c3de94412d53c3dc2f7a8d5

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True
  entry_points:
    - mercantile=mercantile.scripts:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - click >=3.0

test:
  imports:
    - mercantile
    - mercantile.scripts
  commands:
    - mercantile --help

about:
  home: https://github.com/sgillies/mercantile
  license: BSD 3-Clause
  summary: 'Spherical mercator and XYZ tile utilities.'
  license_family: BSD

extra:
  recipe-maintainers:
    - ocefpaf
