{% set version = "1.1.6" %}

package:
  name: mercantile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mercantile/mercantile-{{ version }}.tar.gz
  sha256: 0dff4cbc2c92ceca0e0dfbb3dc74392a96d33cfa29afb1bdfcc80283d3ef4207

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mercantile=mercantile.scripts:cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - click >=3.0

test:
  imports:
    - mercantile
    - mercantile.scripts
  commands:
    - mercantile --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sgillies/mercantile
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Spherical mercator and XYZ tile utilities
  license_family: BSD

extra:
  recipe-maintainers:
    - ocefpaf
