{% set version = "1.0.1" %}

package:
  name: mercantile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mercantile/mercantile-{{ version }}.tar.gz
  sha256: f3160d4c65d60dec6cd8ea31dfbeb0c4ed5512048577be56af66fbd0caaa59f8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True
  entry_points:
    - mercantile=mercantile.scripts:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - click >=3.0

test:
  imports:
    - mercantile
    - mercantile.scripts
  commands:
    - mercantile --help

about:
  home: https://github.com/sgillies/mercantile
  license: BSD 3-Clause
  summary: 'Spherical mercator and XYZ tile utilities.'
  license_family: BSD

extra:
  recipe-maintainers:
    - ocefpaf
