travis:
  secure:
    BINSTAR_TOKEN: fIetm4M8qFfsCS80I7aaJR5FfQ4JV7kuAXbaKCCh3R5xDQCVh7cTFCEcCQYdCwFgOZzdEi8PYOCLElnHbYNeFoOVSB9CqCZT46qZy4XGUe1Dqqa7+vIgqcbk7jipFWeSQwEHQDS1fNMms9TVBidYsjau+0KVjJNv/Sc4lYcJSrrbzavHggqie4fDu8Tswo9y1gCVN3dO+mOz1CUkAZY+I997X+qFaTr2gSJFYA0uqesfVIGf4or+tstejcc2ejFU11x8UO6GqM6mBHw0U1lYB5lPiTCjfdJOThY7vCV7Z1yhNAyoMcCFLdw4muV9dU/4vV/JLTKRu/yb41xhG/ZgW7TN4t0KaRItOeamUdwTT2JD/p/mVxm98s1lMhOFZQ3Y6l8gVXKoR9sdqOOlkmUUucmghl+kUWixX6OW+6i3TYjY0/oOlcj/2cDxx4tOJg8aZxGcZf+mT1CN8v423f+Uu402AjOcexwDMybXSACH+Lqr0swUmmoegUq1JvfHOo4M+J5lJxIaSLbcY/ES+EZ8kk7tGjErhS7aA3FwOyqhorl8qOF/w0tfLao3LxujBZfy+e8XoCcO1XdBPed7XEZR0mUNuYhSahiZ3+ZphqWjjc7LeYjDYlQuDpNianUSIJjsw1zgsff0KoUI75R/HtEYlelF7yseMlRebPDjrLxidwE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
