travis:
  secure:
    BINSTAR_TOKEN: q2jMz+Ct3OaHXag0W5AY4iwZiFEYHZH2K3TXYKSwL9QMXeIFJmdFZ0DG2IkO8NjcLpI7ovp0tab6fAsq/hYFy7+NpK+14sXe0HfAp6FrFpytGUTW+KS1KmkPU+BJFSkmvVglwYRPboBSzWMkgu6yc9s9clASkm8wib3ZERLBlaDqq7DNHFHIQdQQz9EbMWCvvs6CEaLfhVC5Taww6dKtXyydi+gzTIngynFTiF/+ubOR8sZ7S7BMD0lBazMfYGw7XLRGTIO130gaY34CD4RDxsBkJ5L89fCvlOS5heFi2jodzFwmBWsj3gGV1/A1I2iWQtyMtvNgRuvHKKDdoSxizfsfH4mOhvohpLWwRo49GvmmhL7U3+LeKY//AASOTF5zzNPPwWKBVmcXp0gUTIqz3Y+QQp3cH5zJkgN+KxXt8xfpzU9w8u011FmbU9kzvA5XX3LHjdToA1wl9TLM5C0k0mkgBD9MkZwF19kaW3EAPFfPTa63iF+soE0h1WnvIKuNetvnLXUkRSr4Joj/vIwWa6Ztb8TTpB/ske+fcntHx/BiKZ/TRX/i2ZPWUht5eIGN2IigLqg7CG3X57SfmEoqvR4LdmNBrFCt0RW/61NlSZJxqABWmErRMW4IKDLRPaHljiRuIob5qC40muRKfBuYdAs+Sj1PJrpIIwEjB423ko4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
