travis:
  secure:
    BINSTAR_TOKEN: u8VqkdcjyV5skyhKUHdf+MsKHpRdkGGan75KbDuWSNKnX7EK0KWX06pB1xFqmJofblY1bNJRauWr6DY1TsWxxnm7JKiIQqoH9qczZZcJ0eLLifY6P2IRu40KQUQPsyKJYHgITznMFx4y7chvfT8iMckj0Cl6hCKsirP9rInYcyb+3PhMPqie+9BhHnB0w2XGCkbKNPoW9MSyVan21TJ/Ky7SazbB+glWW87LAedqOW8B+tOKsbyM3xMD3OOpIt6soee955nahWTbqObMURHnHrsczA7TbhQCrOY9egcubEUU+bH5ol5hAuMVPST1q0nHaw+8traml/IecVN/qCpOQrStzDzFa+U7RrBist5AMPoWJ17lKfhNArboVccR/6kH6+34Lz+KzIOSEmCoeXCXcuxu50G87znXhiG+DUTvVJUE4U8ZyOPzFe26NfnsOBAOazbBQEdt3Hg1e+6QPRH7IMErALxXtq0+1l84Vg+p/JvnXkLwtwpFOUp7FKCJQpA9yzu0WkcFCdYECjfFduj86LAuqocV11slhbjQJfsaaN/HMy2LX11Oc9OWXGPkhQFWKl9iSa2dxUbQrR4CTzLWV7UZE0gHBLkXiSiFEpftWkVTKf3DM541eSRrBbFkSX+qjvyym/uNlHJWBiWtKPPgbIxVyh2smFp/kyIpOr4FhA0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
